### ISSUE TITLE
Add ability to pin Terraform Enterprise version

### ISSUE THREAD

**Issue by sudomateo** [hashicorp/terraform-aws-terraform-enterprise#30]
Hello,

This issue is to track adding the ability to pin the Terraform Enterprise version that is installed by this module. In non-clustered installations this was configured using `ReleaseSequence` within the `/etc/replicated.conf` file.

**Comment by bnferguson** [comment]
Oh this is strange, this was actually done already but now it seems to be missing. Looks like it didn't make the jump from the original internal repo to the open source module. It's still in the old version, I'll see about getting this in next week. Looks like it made the jump to the Azure and Google modules just fine. Likely a timing issue of when things got merged vs broken out. 

Sorry about that!
