### ISSUE TITLE
Module is specific to v0.11.x will not work for v0.12

### ISSUE THREAD

**Issue by DMonCode** [hashicorp/terraform-aws-terraform-enterprise#35]
I have ran into multiple issues trying to use this module with TF v0.12.13 and I am still working through them.

Can documentation be update to reflect the known working version this module should be used with?

Some key breaking areas are handling variable lists. 
Example:
```
resource "aws_security_group_rule" "allow_list" {
  count             = "${length(var.allow_list) > 0 ? 1 : 0}"
  type              = "ingress"
  protocol          = "-1"
  from_port         = 0
  to_port           = 0
  cidr_blocks       = ["${var.allow_list}"]
  security_group_id = "${aws_security_group.intra_vpc_and_egress.id}"
} 
```

This breaks because `var.allow_list` is a list. Had to change to 
```
cidr_blocks  = var.allow_list
```
To get plan to move past that error. I'm still working through the errors as I need version 0.12 in my current setup.

**Comment by DMonCode** [comment]
I had started down that path but really at this point I would just like clarity in the repo documentation that this is specific to v0.11

There are some compatibility issues with v0.12.14 Namely the 
```
Incorrect attribute value type
  on modules/terraform-aws-terraform-enterprise/modules/lb/security-groups.tf line 71, in resource "aws_security_group" "lb_public":
  71:     cidr_blocks = ["${var.public_subnets_cidr_blocks}"]

Inappropriate value for attribute "cidr_blocks": element 0: string required.
```

Eveitably I would correct one issue and just run into another usually all related to the change in using "${}" vs not using it.

I can run my current deployment agains v0.11.14 with no issue but if I try to use v0.12.14 I will run into problems like the one listed above.

**Comment by ppruthi** [comment]
Ran into the same issues as well. +1 to updating the documentation.

**Comment by bnferguson** [comment]
This is fixed by https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/45 which adds 0.12 support and makes note of version requirements (and existence of the v0.1 branch which supports 0.11)
