### ISSUE TITLE
Airgap Install Examples make external calls

### ISSUE THREAD

**Issue by mocofound** [hashicorp/terraform-aws-terraform-enterprise#38]
For v5 architecture, the airgapped install example appears to use 'external' resources like the public module registry (to get modules) and s3 buckets (to get the installer bits).  Airgapped implies that the install will not require any sort of external internet access.

Airgapped installer example code:
https://github.com/hashicorp/terraform-aws-terraform-enterprise/blob/master/examples/airgap/main.tf

Calling v5 module from public module registry:
`module "terraform-enterprise" {
  source  = "hashicorp/terraform-enterprise/aws"
  version = "0.1.0"
...
}`

Calling external s3 bucket:
`installer_url = "https://${local.setup_bucket}.s3-${local.region}.amazonaws.com/tfe-setup/ptfe.zip"`

**Comment by evanphx** [comment]
You need to set the ptfe_installer_url and airgap_installer_url to ones that are local to you to have it be fully airgapped.

In the case of the example airgap, the idea is that the setup bucket is private to the VPC performing the installer.

**Comment by evanphx** [comment]
Additionally, TFE airgapping does still require either access to releases.hashicorp.com or that users upload their own bundles with all the providers they require: https://www.terraform.io/docs/enterprise/before-installing/network-requirements.html
