### ISSUE TITLE
Primary TFE instances do not have access to internet

### ISSUE THREAD

**Issue by gfysaris** [hashicorp/terraform-aws-terraform-enterprise#50]
Hello,
I've noticed that all primary tfe instances do not have access to internet (egress rule is missing).
Without the access some updates are failing. Is this an expected behaviour?

I did enable the access by adding the following egress rule:
```
resource "aws_security_group" "allow_ptfe" {
...
...
  egress {
    description = "Allow EC2 to have access to internet"

    from_port = 0
    to_port   = 0
    protocol  = "-1"

    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

**Comment by erindatkinson** [comment]
Thanks for submitting this! We had just realized this yesterday so a PR should be forthcoming!
