### ISSUE TITLE
primary_count variable is ignored

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform-aws-terraform-enterprise#60]
The [primary count variable](https://github.com/hashicorp/terraform-aws-terraform-enterprise/blob/24b57f151b0b8fc3c3049c2a110c18ba96117241/variables.tf#L111) is ignored, because the number of primaries is hard-coded to 3.

**Comment by gfysaris** [comment]
https://github.com/hashicorp/terraform-aws-terraform-enterprise/blob/master/primary.tf

```
resource "aws_instance" "primary" {
  # The number of primaries must be hard coded to 3 always for now.
  # In the future we'll allow for different variables of primary, but it
  # make sense to constrain the domain of problem related to primary counts
  # for now.
  count = 3
```

As the comment mentions.. **it must be hard-coded**

**Comment by ryanking** [comment]
@gfysaris i see that now, but I think it is still confusing for users. Why remove the variable if it is not used?
